import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CASE_DIR = ROOT / "data" / "normalized" / "case_reports"
FP_DIR = ROOT / "data" / "normalized" / "false_positive_cases"

POLLUTED_TAGS = {
    "high",
    "medium",
    "low",
    "qa",
    "non-critical",
    "ethena",
    "kinetiq",
    "reserve",
    "angle",
    "noya",
    "spectra",
    "dyad",
    "althea",
    "nudgexyz",
}


def _load_json_files(directory: Path):
    for path in sorted(directory.glob("*.json")):
        yield path, json.loads(path.read_text(encoding="utf-8"))


def test_case_reports_do_not_use_autogenerated_root_cause_prefixes() -> None:
    bad = []
    for path, data in _load_json_files(CASE_DIR):
        root_cause = data.get("root_cause", "")
        if (
            root_cause.startswith("Report-described")
            or root_cause.startswith("protocol invariant violation in")
            or root_cause.startswith("state/accounting validation gap in")
        ):
            bad.append(path.name)
    assert bad == []


def test_case_reports_do_not_use_generic_condition_described_invariants() -> None:
    bad = []
    for path, data in _load_json_files(CASE_DIR):
        invariants = " ".join(data.get("broken_invariants", []))
        if "condition described by" in invariants:
            bad.append(path.name)
    assert bad == []


def test_semantic_tags_do_not_contain_protocol_or_severity_words() -> None:
    bad = []
    for directory in [CASE_DIR, FP_DIR]:
        for path, data in _load_json_files(directory):
            polluted = [tag for tag in data.get("tags", []) if tag.lower() in POLLUTED_TAGS]
            if polluted:
                bad.append((path.name, polluted))
    assert bad == []
